### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by captncanary** [JakubPetriska/poker-cfr#3]
Hi Jakub. I'm trying to run train.py in Spyder but am getting an error. I got the acpc client import to work by adding its path in spyder. Below is the output when I run train.py. Are you able to help? Thanks.

Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

runfile('D:/Users/Stephen/Documents/Python/poker-agent-kit/train.py', wdir='D:/Users/Stephen/Documents/Python/poker-agent-kit')
Traceback (most recent call last):

  File "<ipython-input-1-463f0e48a044>", line 1, in <module>
    runfile('D:/Users/Stephen/Documents/Python/poker-agent-kit/train.py', wdir='D:/Users/Stephen/Documents/Python/poker-agent-kit')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Users/Stephen/Documents/Python/poker-agent-kit/train.py", line 3, in <module>
    import acpc_python_client as acpc

  File "D:\Users\Stephen\Documents\Python\acpc-python-client\acpc_python_client\__init__.py", line 1, in <module>
    from acpc_python_client.agent import Client

  File "D:\Users\Stephen\Documents\Python\acpc-python-client\acpc_python_client\agent.py", line 4, in <module>
    import acpc_python_client.agent_lib as lib

  File "D:\Users\Stephen\Documents\Python\acpc-python-client\acpc_python_client\agent_lib\__init__.py", line 7, in <module>
    player = CDLL(lib_file_path)

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

**Comment by JakubPetriska** [comment]
Unfortunately I don't think the library can be run in Windows because the way the native part is built was done specifically for Linux and Linux only. Do you use Windows 10? Is it possible to use the built-in bash shell?

**Comment by captncanary** [comment]
Yes, I'm on Windows 10. I have Git bash installed and cygwin. Are you suggesting I try to run it using one of those? Could you give me some instructions to try please?

**Comment by JakubPetriska** [comment]
Yes that's what I mean. Nothing should differ in terms of using the library so you can use the README files in both projects. In case of Anaconda installation into either cygwin or bash in Windows 10 I am not able to help you there.
